export default {
   "air":"空氣",
   "stone":"石頭",
   "grass":"草地",
   "dirt":"泥土",
   "cobblestone":"鵝卵石",
   "planks":"木材",
   "sapling":"樹苗",
   "bedrock":"基岩",
   "flowing_water":"水",
   "water":"靜態水",
   "flowing_lava":"熔岩",
   "lava":"靜態熔岩",
   "sand":"沙",
   "gravel":"礫石",
   "gold_ore":"金礦",
   "iron_ore":"鐵礦",
   "coal_ore":"煤礦",
   "log‌‌":"原木",
   "leaves":"樹葉",
   "sponge":"海綿",
   "glass":"玻璃",
   "lapis_ore":"青金石礦",
   "lapis_block":"青金石方塊",
   "dispenser":"發射器",
   "sandstone":"砂岩",
   "noteblock":"音階盒",
   "bed":"床",
   "golden_rail":"動力鐵軌",
   "detector_rail":"感測鐵軌",
   "sticky_piston":"黏性活塞",
   "web":"蜘蛛網",
   "tallgrass":"芒草",
   "deadbush":"枯灌木",
   "piston":"活塞",
   "pistonarmcollision":"活塞臂",
   "wool":"羊毛",
   // "element_0":"未知元素（???）",
   "yellow_flower":"蒲公英",
   "red_flower":"花",
   "brown_mushroom":"棕色蘑菇",
   "red_mushroom":"紅色蘑菇",
   "gold_block":"黃金方塊",
   "iron_block":"鐵方塊",
   "double_stone_slab":"雙石半磚",
   "stone_slab":"石半磚",
   "brick_block":"紅磚",
   "tnt":"TNT",
   "bookshelf":"書櫃",
   "mossy_cobblestone":"青苔鵝卵石",
   "obsidian":"黑曜石",
   "torch":"火把",
   "fire":"火",
   "mob_spawner":"生怪磚",
   "oak_stairs":"橡木階梯",
   "chest":"儲物箱",
   "redstone_wire":"紅石線",
   "diamond_ore":"鑽石礦",
   "diamond_block":"鑽石方塊",
   "crafting_table":"工作台",
   "wheat":"小麥",
   "farmland":"耕地",
   "furnace":"熔爐",
   "lit_furnace":"燃燒的熔爐",
   "standing_sign":"橡木告示牌",
   "wooden_door":"橡木門",
   "ladder":"梯子",
   "rail":"鐵軌",
   "stone_stairs":"鵝卵石階梯",
   "wall_sign":"牆上的橡木告示牌",
   "lever":"控制桿",
   "stone_pressure_plate":"石製壓力板",
   "iron_door":"鐵門",
   "wooden_pressure_plate":"木質壓力板",
   "redstone_ore":"紅石礦",
   "lit_redstone_ore":"發光的紅石礦",
   "unlit_redstone_torch":"熄滅的紅石火把",
   "redstone_torch":"紅石火把",
   "stone_button":"石製按鈕",
   "snow_layer":"頂層雪",
   "ice":"冰",
   "snow":"雪",
   "cactus":"仙人掌",
   "clay":"黏土塊",
   "reeds":"甘蔗",
   "jukebox":"唱片機",
   "fence":"橡木柵欄",
   "pumpkin":"南瓜",
   "netherrack":"地獄石",
   "soul_sand":"靈魂砂",
   "glowstone":"螢光石",
   "portal":"地獄傳送門",
   "lit_pumpkin":"南瓜燈",
   "cake":"蛋糕",
   "unpowered_repeater":"紅石中繼器 （未開啟）",
   "powered_repeater":"紅石中繼器 （已開啟）",
   "invisibleBedrock":"隱形的基岩",
   "trapdoor":"地板門",
   "monster_egg":"蛀蝕的方塊",
   "stonebrick":"石磚",
   "brown_mushroom_block":"棕色蘑菇方塊",
   "red_mushroom_block":"紅色蘑菇方塊",
   "iron_bars":"鐵柵欄",
   "glass_pane":"玻璃片",
   "melon_block":"西瓜",
   "pumpkin_stem":"南瓜梗",
   "melon_stem":"西瓜梗",
   "vine":"藤蔓",
   "fence_gate":"橡木柵欄門",
   "brick_stairs":"紅磚樓梯",
   "stone_brick_stairs":"石磚階梯",
   "mycelium":"菌絲土",
   "waterlily":"荷葉",
   "nether_brick":"地獄磚頭",
   "nether_brick_fence":"地獄磚柵欄",
   "nether_brick_stairs":"地獄磚階梯",
   "nether_wart":"地獄疙瘩",
   "enchanting_table":"附魔台",
   "brewing_stand":"釀造台",
   "cauldron":"鍋釜",
   "end_portal":"終界傳送門方塊",
   "end_portal_frame":"終界傳送門框架",
   "end_stone":"終界石",
   "dragon_egg":"龍蛋",
   "redstone_lamp":"紅石燈 （未開啟）",
   "lit_redstone_lamp":"紅石燈 （已開啟）",
   "dropper":"投擲器",
   "activator_rail":"觸發鐵軌",
   "cocoa":"可可豆",
   "sandstone_stairs":"砂岩階梯",
   "emerald_ore":"綠寶石礦",
   "ender_chest":"終界箱",
   "tripwire_hook":"絆線鉤",
   "tripwire":"絆線",
   "emerald_block":"綠寶石方塊",
   "spruce_stairs":"杉木階梯",
   "birch_stairs":"樺木階梯",
   "jungle_stairs":"叢林木階梯",
   "command_block":"脈衝型指令方塊",
   "beacon":"烽火台",
   "cobblestone_wall":"鵝卵石牆",
   "flower_pot":"花盆",
   "carrots":"胡蘿蔔",
   "potatoes":"馬鈴薯",
   "wooden_button":"橡木按鈕",
   "skull":"生物頭顱",
   "anvil":"鐵砧",
   "trapped_chest":"陷阱儲物箱",
   "light_weighted_pressure_plate":"測重壓力板 （輕質）",
   "heavy_weighted_pressure_plate":"測重壓力板 （重質）",
   "unpowered_comparator":"紅石比較器 （未開啟）",
   "powered_comparator":"紅石比較器 （已開啟）",
   "daylight_detector":"陽光探測器",
   "redstone_block":"紅石方塊",
   "quartz_ore":"地獄石英礦",
   "hopper":"漏斗",
   "quartz_block":"石英方塊",
   "quartz_stairs":"石英階梯",
   "double_wooden_slab":"雙木半磚",
   "wooden_slab":"木質半磚",
   "stained_hardened_clay":"染色陶土",
   "stained_glass_pane":"染色玻璃片",
   "leaves2":"相思木樹葉",
   "log2":"相思木原木",
   "acacia_stairs":"相思木階梯",
   "dark_oak_stairs":"黑橡木階梯",
   "slime":"史萊姆方塊",
   "iron_trapdoor":"鐵製地板門",
   "prismarine":"海磷石",
   "seaLantern":"海燈籠",
   "hay_block":"乾草捆",
   "carpet":"地毯",
   "hardened_clay":"陶土",
   "coal_block":"煤炭方塊",
   "packed_ice":"冰磚",
   "double_plant":"向日葵",
   "standing_banner":"站立的旗幟",
   "wall_banner":"牆上的旗幟",
   "daylight_detector_inverted":"反向陽光探測器",
   "red_sandstone":"紅砂岩",
   "red_sandstone_stairs":"紅砂岩階梯",
   "double_stone_slab2":"雙紅砂岩半磚",
   "stone_slab2":"紅砂岩半磚",
   "spruce_fence_gate":"杉木柵欄門",
   "birch_fence_gate":"樺木柵欄門",
   "jungle_fence_gate":"叢林木柵欄門",
   "dark_oak_fence_gate":"黑橡木柵欄門",
   "acacia_fence_gate":"相思木柵欄門",
   "repeating_command_block":"重複型指令方塊",
   "chain_command_block":"連鎖式指令方塊",
   "hard_glass_pane":"強化玻璃片",
   "hard_stained_glass_pane":"染色強化玻璃片",
   "chemical_heat":"加熱塊",
   "spruce_door":"杉木門",
   "birch_door":"樺木門",
   "jungle_door":"叢林木門",
   "acacia_door":"相思木門",
   "dark_oak_door":"黑橡木門",
   "grass_path":"草徑",
   "frame":"物品展示框",
   "chorus_flower":"歌萊花",
   "purpur_block":"紫珀方塊",
   "colored_torch_rg":"紅色火把",
   "purpur_stairs":"紫珀磚階梯",
   "colored_torch_bp":"藍色火把",
   "undyed_shulker_box":"未染色的界伏盒",
   "end_bricks":"終界石磚",
   "frosted_ice":"霜冰",
   "end_rod":"終界燭",
   "end_gateway":"終界折躍門方塊",
   "magma":"岩漿塊",
   "nether_wart_block":"地獄疙瘩塊",
   "red_nether_brick":"紅地獄磚",
   "bone_block":"骨塊",
   "structure_void":"結構空位",
   "shulker_box":"界伏盒",
   "purple_glazed_terracotta":"紫色釉陶",
   "white_glazed_terracotta":"白色釉陶",
   "orange_glazed_terracotta":"橙色釉陶",
   "magenta_glazed_terracotta":"洋紅色釉陶",
   "light_blue_glazed_terracotta":"淺藍色釉陶",
   "yellow_glazed_terracotta":"黃色釉陶",
   "lime_glazed_terracotta":"淺綠色釉陶",
   "pink_glazed_terracotta":"粉紅色釉陶",
   "gray_glazed_terracotta":"灰色釉陶",
   "silver_glazed_terracotta":"淺灰色釉陶",
   "cyan_glazed_terracotta":"青色釉陶",
   "blue_glazed_terracotta":"藍色釉陶",
   "brown_glazed_terracotta":"棕色釉陶",
   "green_glazed_terracotta":"綠色釉陶",
   "red_glazed_terracotta":"紅色釉陶",
   "black_glazed_terracotta":"黑色釉陶",
   "concrete":"混凝土",
   "concrete_powder":"混凝土粉末",
   "chemistry_table":"化合物創建器",
   "underwater_torch":"水下火把",
   "chorus_plant":"歌萊枝",
   "stained_glass":"染色玻璃",
   // "camera":"相機  [注 1]",
   "podzol":"灰壤",
   "beetroot":"甜菜",
   "stonecutter":"切石機",
   "glowingobsidian":"發光的黑曜石",
   "netherreactor":"地獄反應核",
   // "info_update":"數據更新方塊（update!） [注 2]",
   // "info_update2":"數據更新方塊（ate!upd）",
   // "movingBlock":"被活塞推動的方塊",
   "observer":"偵測器",
   "structure_block":"結構方塊",
   "hard_glass":"強化玻璃",
   "hard_stained_glass":"強化染色玻璃",
   "reserved6":"reserved6",
   "prismarine_stairs":"海磷石頭階梯",
   "dark_prismarine_stairs":"暗海磷石頭階梯",
   "prismarine_bricks_stairs":"海磷石磚階梯",
   "stripped_spruce_log":"剝皮杉木原木",
   "stripped_birch_log":"剝皮樺木原木",
   "stripped_jungle_log":"剝皮叢林木原木",
   "stripped_acacia_log":"剝皮相思木原木",
   "stripped_dark_oak_log":"剝皮黑橡木原木",
   "stripped_oak_log":"剝皮橡木原木",
   "blue_ice":"藍冰",
   // "element_1":"氫",
   // "element_2":"氦",
   // "element_3":"鋰",
   // "element_4":"鈹",
   // "element_5":"硼",
   // "element_6":"碳",
   // "element_7":"氮",
   // "element_8":"氧",
   // "element_9":"氟",
   // "element_10":"氖",
   // "element_11":"鈉",
   // "element_12":"鎂",
   // "element_13":"鋁",
   // "element_14":"矽",
   // "element_15":"磷",
   // "element_16":"硫",
   // "element_17":"氯",
   // "element_18":"氬",
   // "element_19":"鉀",
   // "element_20":"鈣",
   // "element_21":"鈧",
   // "element_22":"鈦",
   // "element_23":"釩",
   // "element_24":"鉻",
   // "element_25":"錳",
   // "element_26":"鐵",
   // "element_27":"鈷",
   // "element_28":"鎳",
   // "element_29":"銅",
   // "element_30":"鋅",
   // "element_31":"鎵",
   // "element_32":"鍺",
   // "element_33":"砷",
   // "element_34":"硒",
   // "element_35":"溴",
   // "element_36":"氪",
   // "element_37":"銣",
   // "element_38":"鍶",
   // "element_39":"釔",
   // "element_40":"鋯",
   // "element_41":"鈮",
   // "element_42":"鉬",
   // "element_43":"鎝",
   // "element_44":"釕",
   // "element_45":"銠",
   // "element_46":"鈀",
   // "element_47":"銀",
   // "element_48":"鎘",
   // "element_49":"銦",
   // "element_50":"錫",
   // "element_51":"銻",
   // "element_52":"碲",
   // "element_53":"碘",
   // "element_54":"氙",
   // "element_55":"銫",
   // "element_56":"鋇",
   // "element_57":"鑭",
   // "element_58":"鈰",
   // "element_59":"鐠",
   // "element_60":"釹",
   // "element_61":"鉕",
   // "element_62":"釤",
   // "element_63":"銪",
   // "element_64":"釓",
   // "element_65":"鋱",
   // "element_66":"鏑",
   // "element_67":"鈥",
   // "element_68":"鉺",
   // "element_69":"銩",
   // "element_70":"鐿",
   // "element_71":"鎦",
   // "element_72":"鉿",
   // "element_73":"鉭",
   // "element_74":"鎢",
   // "element_75":"錸",
   // "element_76":"鋨",
   // "element_77":"銥",
   // "element_78":"鉑",
   // "element_79":"金",
   // "element_80":"汞",
   // "element_81":"鉈",
   // "element_82":"鉛",
   // "element_83":"鉍",
   // "element_84":"釙",
   // "element_85":"砹",
   // "element_86":"氡",
   // "element_87":"鍅",
   // "element_88":"鐳",
   // "element_89":"錒",
   // "element_90":"釷",
   // "element_91":"鏷",
   // "element_92":"鈾",
   // "element_93":"錼",
   // "element_94":"鈽",
   // "element_95":"鋂",
   // "element_96":"鋦",
   // "element_97":"鉳",
   // "element_98":"鉲",
   // "element_99":"鑀",
   // "element_100":"鐨",
   // "element_101":"鍆",
   // "element_102":"鍩",
   // "element_103":"鐒",
   // "element_104":"鑪",
   // "element_105":"𨧀",
   // "element_106":"𨭎",
   // "element_107":"𨨏",
   // "element_108":"𨭆",
   // "element_109":"䥑",
   // "element_110":"鐽",
   // "element_111":"錀",
   // "element_112":"鎶",
   // "element_113":"鉨",
   // "element_114":"鈇",
   // "element_115":"鏌",
   // "element_116":"鉝",
   // "element_117":"Tennessine",
   // "element_118":"Oganesson",
   "seagrass":"海草",
   "coral":"珊瑚",
   "coral_block":"珊瑚方塊",
   "coral_fan":"扇狀珊瑚",
   "coral_fan_dead":"死亡的扇狀珊瑚",
   "coral_fan_hang":"牆上的扇狀珊瑚",
   "coral_fan_hang2":"牆上的扇狀珊瑚",
   "coral_fan_hang3":"牆上的扇狀珊瑚",
   "kelp":"海帶",
   "dried_kelp_block":"海帶乾塊",
   "acacia_button":"相思木按鈕",
   "birch_button":"樺木按鈕",
   "dark_oak_button":"黑橡木按鈕",
   "jungle_button":"叢林木按鈕",
   "spruce_button":"杉木按鈕",
   "acacia_trapdoor":"相思木地板門",
   "birch_trapdoor":"樺木地板門",
   "dark_oak_trapdoor":"黑橡木地板門",
   "jungle_trapdoor":"叢林木地板門",
   "spruce_trapdoor":"杉木地板門",
   "acacia_pressure_plate":"相思木壓力板",
   "birch_pressure_plate":"樺木壓力板",
   "dark_oak_pressure_plate":"黑橡木壓力板",
   "jungle_pressure_plate":"叢林木壓力板",
   "spruce_pressure_plate":"杉木壓力板",
   "carved_pumpkin":"雕刻過的南瓜",
   "sea_pickle":"海鞘",
   "conduit":"海靈核心",
   "turtle_egg":"海龜蛋",
   "bubble_column":"氣泡柱",
   "barrier":"屏障",
   "stone_slab3":"終界石磚半磚",
   "bamboo":"竹子",
   "bamboo_sapling":"竹荀",
   "scaffolding":"鷹架",
   "stone_slab4":"青苔石磚半磚",
   "double_stone_slab3":"雙層終界石磚半磚",
   "double_stone_slab4":"雙層青苔石磚半磚",
   "granite_stairs":"花崗岩階梯",
   "diorite_stairs":"閃長岩階梯",
   "andesite_stairs":"安山岩階梯",
   "polished_granite_stairs":"拋光花崗岩階梯",
   "polished_diorite_stairs":"拋光閃長岩階梯",
   "polished_andesite_stairs":"拋光安山岩階梯",
   "mossy_stone_brick_stairs":"青苔石磚階梯",
   "smooth_red_sandstone_stairs":"平滑紅砂岩階梯",
   "smooth_sandstone_stairs":"平滑砂岩階梯",
   "end_brick_stairs":"終界石磚階梯",
   "mossy_cobblestone_stairs":"青苔鵝卵石階梯",
   "normal_stone_stairs":"石頭階梯",
   "spruce_standing_sign":"杉木告示牌",
   "spruce_wall_sign":"牆上的杉木告示牌",
   "smooth_stone":"平滑石頭",
   "red_nether_brick_stairs":"紅地獄磚階梯",
   "smooth_quartz_stairs":"石英階梯",
   "birch_standing_sign":"樺木告示牌",
   "birch_wall_sign":"牆上的樺木告示牌",
   "jungle_standing_sign":"叢林木告示牌",
   "jungle_wall_sign":"牆上的叢林木告示牌",
   "acacia_standing_sign":"相思木告示牌",
   "acacia_wall_sign":"牆上的相思木告示牌",
   "darkoak_standing_sign":"黑橡木告示牌",
   "darkoak_wall_sign":"牆上的黑橡木告示牌",
   "lectern":"講台",
   "grindstone":"砂輪",
   "blast_furnace":"高爐",
   "stonecutter_block":"切石機",
   "smoker":"煙燻爐",
   "lit_smoker":"燃燒的煙燻爐",
   "cartography_table":"製圖台",
   "fletching_table":"製箭台",
   "smithing_table":"鍛造台",
   "barrel":"木桶",
   "loom":"紡織機",
   "bell":"鐘",
   "sweet_berry_bush":"甜莓灌木叢",
   "lantern":"燈籠",
   "campfire":"營火",
   "lava_cauldron":"裝有熔岩的鍋釜",
   "jigsaw":"拼圖方塊",
   "wood":"木塊",
   "composter":"堆肥桶",
   "lit_blast_furnace":"燃燒的高爐",
   "light_block":"光源方塊",
   "wither_rose":"凋零玫瑰",
   "stickypistonarmcollision":"黏性活塞臂",
   "bee_nest":"蜂窩",
   "beehive":"蜂箱",
   "honey_block":"蜂蜜塊",
   "honeycomb_block":"蜂巢塊",
   // "lodestone":"磁石",
   // "crimson_roots":"緋紅蕈根",
   // "warped_roots":"扭曲蕈根",
   // "crimson_stem":"緋紅蕈柄",
   // "warped_stem":"扭曲蕈柄",
   // "warped_wart_block":"扭曲疙瘩塊",
   // "crimson_fungus":"緋紅蕈菇",
   // "warped_fungus":"扭曲蕈菇",
   // "shroomlight":"蕈光體",
   // "weeping_vines":"垂泣藤",
   // "crimson_nylium":"緋紅菌絲石",
   // "warped_nylium":"扭曲菌絲石",
   // "basalt":"玄武岩",
   // "polished_basalt":"拋光玄武岩",
   // "soul_soil":"靈魂土",
   // "soul_fire":"靈魂火",
   // "nether_sprouts":"地獄芽",
   // "target":"標靶",
   // "stripped_crimson_stem":"剝皮緋紅蕈柄",
   // "stripped_warped_stem":"剝皮扭曲蕈柄",
   // "crimson_planks":"緋紅蕈木材",
   // "warped_planks":"扭曲蕈木材",
   // "crimson_door":"緋紅蕈木門",
   // "warped_door":"扭曲蕈木門",
   // "crimson_trapdoor":"緋紅蕈木地板門",
   // "warped_trapdoor":"扭曲蕈木地板門",
   // "crimson_sign":"緋紅蕈木告示牌",
   // "warped_sign":"扭曲蕈木告示牌",
   // "crimson_wall_sign":"牆上的緋紅蕈木告示牌",
   // "warped_wall_sign":"牆上的扭曲蕈木告示牌",
   // "crimson_stairs":"緋紅蕈木階梯",
   // "warped_stairs":"扭曲蕈木階梯",
   // "crimson_fence":"緋紅蕈木柵欄",
   // "warped_fence":"扭曲蕈木柵欄",
   // "crimson_fence_gate":"緋紅蕈木柵欄門",
   // "warped_fence_gate":"扭曲蕈木柵欄門",
   // "crimson_button":"緋紅蕈木按鈕",
   // "warped_button":"扭曲蕈木按鈕",
   // "crimson_pressure_plate":"緋紅蕈木壓力板",
   // "warped_pressure_plate":"扭曲蕈木壓力板",
   // "crimson_slab":"緋紅蕈木半磚",
   // "warped_slab":"扭曲蕈木半磚",
   // "crimson_double_slab":"雙層緋紅蕈木半磚",
   // "warped_double_slab":"雙層扭曲蕈木半磚",
   // "soul_torch":"靈魂火把",
   // "soul_lantern":"靈魂燈籠",
   // "netherite_block":"獄髓方塊",
   // "ancient_debris":"遠古遺骸",
   // "respawn_anchor":"重生錨",
   // "blackstone":"黑石",
   // "polished_blackstone_bricks":"拋光黑石磚",
   // "polished_blackstone_brick_stairs":"拋光黑石磚階梯",
   // "blackstone_stairs":"黑石頭階梯",
   // "blackstone_wall":"黑石牆",
   // "polished_blackstone_brick_wall":"拋光黑石磚牆",
   // "chiseled_polished_blackstone":"鏨制拋光黑石",
   // "cracked_polished_blackstone_bricks":"裂紋拋光黑石磚",
   // "gilded_blackstone":"鑲金黑石",
   // "blackstone_slab":"黑石半磚",
   // "blackstone_double_slab":"雙層黑石半磚",
   // "polished_blackstone_brick_slab":"拋光黑石磚半磚",
   // "polished_blackstone_brick_double_slab":"雙層拋光黑石磚半磚",
   // "chain":"鎖鏈",
   // "twisting_vines":"扭曲藤",
   // "nether_gold_ore":"地獄金礦",
   // "crying_obsidian":"哭泣的黑曜石",
   // "soul_campfire":"靈魂營火",
   // "polished_blackstone":"拋光黑石",
   // "polished_blackstone_stairs":"拋光黑石頭階梯",
   // "polished_blackstone_slab":"拋光黑石半磚",
   // "polished_blackstone_double_slab":"雙層拋光黑石半磚",
   // "polished_blackstone_pressure_plate":"拋光黑石壓力板",
   // "polished_blackstone_button":"拋光黑石按鈕",
   // "polished_blackstone_wall":"拋光黑石牆",
   // "warped_hyphae":"扭曲菌絲體",
   // "crimson_hyphae":"緋紅菌絲體",
   // "stripped_crimson_hyphae":"剝皮緋紅菌絲體",
   // "stripped_warped_hyphae":"剝皮扭曲菌絲體",
   // "chiseled_nether_bricks":"鏨制地獄磚",
   // "cracked_nether_bricks":"裂紋地獄磚",
   "quartz_bricks":"石英磚",
   "allow":"允許方塊",
   "deny":"拒絕方塊",
   "border_block":"邊界方塊",
   "chalkboard":"黑板"
}
